export enum CurrencyEnum {
  AED = "AED", // UAE Dirham
  AFN = "AFN", // Afghan Afghani
  ALL = "ALL", // Albanian Lek
  AMD = "AMD", // Armenian Dram
  ANG = "ANG", // Netherlands Antillean Guilder
  AOA = "AOA", // Angolan Kwanza
  ARS = "ARS", // Argentine Peso
  AUD = "AUD", // Australian Dollar
  AWG = "AWG", // Aruban Florin
  AZN = "AZN", // Azerbaijani Manat
  BAM = "BAM", // Bosnia-Herzegovina Convertible Mark
  BBD = "BBD", // Barbadian Dollar
  BDT = "BDT", // Bangladeshi Taka
  BGN = "BGN", // Bulgarian Lev
  BHD = "BHD", // Bahraini Dinar
  BIF = "BIF", // Burundian Franc
  BMD = "BMD", // Bermudian Dollar
  BND = "BND", // Brunei Dollar
  BOB = "BOB", // Bolivian Boliviano
  BRL = "BRL", // Brazilian Real
  BSD = "BSD", // Bahamian Dollar
  BTN = "BTN", // Bhutanese Ngultrum
  BWP = "BWP", // Botswana Pula
  BYN = "BYN", // Belarusian Ruble
  BZD = "BZD", // Belize Dollar
  CAD = "CAD", // Canadian Dollar
  CDF = "CDF", // Congolese Franc
  CHF = "CHF", // Swiss Franc
  CLP = "CLP", // Chilean Peso
  CNY = "CNY", // Chinese Yuan
  COP = "COP", // Colombian Peso
  CRC = "CRC", // Costa Rican Colón
  CUP = "CUP", // Cuban Peso
  CVE = "CVE", // Cape Verdean Escudo
  CZK = "CZK", // Czech Koruna
  DJF = "DJF", // Djiboutian Franc
  DKK = "DKK", // Danish Krone
  DOP = "DOP", // Dominican Peso
  DZD = "DZD", // Algerian Dinar
  EGP = "EGP", // Egyptian Pound
  ERN = "ERN", // Eritrean Nakfa
  ETB = "ETB", // Ethiopian Birr
  EUR = "EUR", // Euro
  FJD = "FJD", // Fijian Dollar
  FKP = "FKP", // Falkland Islands Pound
  GBP = "GBP", // British Pound Sterling
  GEL = "GEL", // Georgian Lari
  GHS = "GHS", // Ghanaian Cedi
  GIP = "GIP", // Gibraltar Pound
  GMD = "GMD", // Gambian Dalasi
  GNF = "GNF", // Guinean Franc
  GTQ = "GTQ", // Guatemalan Quetzal
  GYD = "GYD", // Guyanese Dollar
  HKD = "HKD", // Hong Kong Dollar
  HNL = "HNL", // Honduran Lempira
  HRK = "HRK", // Croatian Kuna
  HTG = "HTG", // Haitian Gourde
  HUF = "HUF", // Hungarian Forint
  IDR = "IDR", // Indonesian Rupiah
  ILS = "ILS", // Israeli Shekel
  INR = "INR", // Indian Rupee
  IQD = "IQD", // Iraqi Dinar
  IRR = "IRR", // Iranian Rial
  ISK = "ISK", // Icelandic Króna
  JMD = "JMD", // Jamaican Dollar
  JOD = "JOD", // Jordanian Dinar
  JPY = "JPY", // Japanese Yen
  KES = "KES", // Kenyan Shilling
  KGS = "KGS", // Kyrgyzstani Som
  KHR = "KHR", // Cambodian Riel
  KMF = "KMF", // Comorian Franc
  KRW = "KRW", // South Korean Won
  KWD = "KWD", // Kuwaiti Dinar
  KYD = "KYD", // Cayman Islands Dollar
  KZT = "KZT", // Kazakhstani Tenge
  LAK = "LAK", // Lao Kip
  LBP = "LBP", // Lebanese Pound
  LKR = "LKR", // Sri Lankan Rupee
  LRD = "LRD", // Liberian Dollar
  LSL = "LSL", // Lesotho Loti
  LYD = "LYD", // Libyan Dinar
  MAD = "MAD", // Moroccan Dirham
  MDL = "MDL", // Moldovan Leu
  MGA = "MGA", // Malagasy Ariary
  MKD = "MKD", // Macedonian Denar
  MMK = "MMK", // Myanmar Kyat
  MNT = "MNT", // Mongolian Tögrög
  MOP = "MOP", // Macanese Pataca
  MRU = "MRU", // Mauritanian Ouguiya
  MUR = "MUR", // Mauritian Rupee
  MVR = "MVR", // Maldivian Rufiyaa
  MWK = "MWK", // Malawian Kwacha
  MXN = "MXN", // Mexican Peso
  MYR = "MYR", // Malaysian Ringgit
  MZN = "MZN", // Mozambican Metical
  NAD = "NAD", // Namibian Dollar
  NGN = "NGN", // Nigerian Naira
  NIO = "NIO", // Nicaraguan Córdoba
  NOK = "NOK", // Norwegian Krone
  NPR = "NPR", // Nepalese Rupee
  NZD = "NZD", // New Zealand Dollar
  OMR = "OMR", // Omani Rial
  PAB = "PAB", // Panamanian Balboa
  PEN = "PEN", // Peruvian Sol
  PGK = "PGK", // Papua New Guinean Kina
  PHP = "PHP", // Philippine Peso
  PKR = "PKR", // Pakistani Rupee
  PLN = "PLN", // Polish Złoty
  PYG = "PYG", // Paraguayan Guaraní
  QAR = "QAR", // Qatari Riyal
  RON = "RON", // Romanian Leu
  RSD = "RSD", // Serbian Dinar
  RUB = "RUB", // Russian Ruble
  RWF = "RWF", // Rwandan Franc
  SAR = "SAR", // Saudi Riyal
  SBD = "SBD", // Solomon Islands Dollar
  SCR = "SCR", // Seychellois Rupee
  SDG = "SDG", // Sudanese Pound
  SEK = "SEK", // Swedish Krona
  SGD = "SGD", // Singapore Dollar
  SHP = "SHP", // Saint Helena Pound
  SLE = "SLE", // Sierra Leonean Leone
  SLL = "SLL", // Sierra Leonean Leone (Old)
  SOS = "SOS", // Somali Shilling
  SRD = "SRD", // Surinamese Dollar
  SSP = "SSP", // South Sudanese Pound
  STN = "STN", // São Tomé and Príncipe Dobra
  SYP = "SYP", // Syrian Pound
  SZL = "SZL", // Swazi Lilangeni
  THB = "THB", // Thai Baht
  TJS = "TJS", // Tajikistani Somoni
  TMT = "TMT", // Turkmenistani Manat
  TND = "TND", // Tunisian Dinar
  TOP = "TOP", // Tongan Paʻanga
  TRY = "TRY", // Turkish Lira
  TTD = "TTD", // Trinidad and Tobago Dollar
  TZS = "TZS", // Tanzanian Shilling
  UAH = "UAH", // Ukrainian Hryvnia
  UGX = "UGX", // Ugandan Shilling
  USD = "USD", // US Dollar
  UYU = "UYU", // Uruguayan Peso
  UZS = "UZS", // Uzbekistani So'm
  VES = "VES", // Venezuelan Bolívar
  VND = "VND", // Vietnamese Đồng
  XAF = "XAF", // Central African CFA Franc
  XCD = "XCD", // East Caribbean Dollar
  XOF = "XOF", // West African CFA Franc
  YER = "YER", // Yemeni Rial
  ZAR = "ZAR", // South African Rand
  ZMW = "ZMW", // Zambian Kwacha
}

export enum CurrencyNameEnum {
  AED = "UAE Dirham",
  AFN = "Afghan Afghani",
  ALL = "Albanian Lek",
  AMD = "Armenian Dram",
  ANG = "Netherlands Antillean Guilder",
  AOA = "Angolan Kwanza",
  ARS = "Argentine Peso",
  AUD = "Australian Dollar",
  AWG = "Aruban Florin",
  AZN = "Azerbaijani Manat",
  BAM = "Bosnia-Herzegovina Convertible Mark",
  BBD = "Barbadian Dollar",
  BDT = "Bangladeshi Taka",
  BGN = "Bulgarian Lev",
  BHD = "Bahraini Dinar",
  BIF = "Burundian Franc",
  BMD = "Bermudian Dollar",
  BND = "Brunei Dollar",
  BOB = "Bolivian Boliviano",
  BRL = "Brazilian Real",
  BSD = "Bahamian Dollar",
  BTN = "Bhutanese Ngultrum",
  BWP = "Botswana Pula",
  BYN = "Belarusian Ruble",
  BZD = "Belize Dollar",
  CAD = "Canadian Dollar",
  CDF = "Congolese Franc",
  CHF = "Swiss Franc",
  CLP = "Chilean Peso",
  CNY = "Chinese Yuan",
  COP = "Colombian Peso",
  CRC = "Costa Rican Colón",
  CUP = "Cuban Peso",
  CVE = "Cape Verdean Escudo",
  CZK = "Czech Koruna",
  DJF = "Djiboutian Franc",
  DKK = "Danish Krone",
  DOP = "Dominican Peso",
  DZD = "Algerian Dinar",
  EGP = "Egyptian Pound",
  ERN = "Eritrean Nakfa",
  ETB = "Ethiopian Birr",
  EUR = "Euro",
  FJD = "Fijian Dollar",
  FKP = "Falkland Islands Pound",
  GBP = "British Pound Sterling",
  GEL = "Georgian Lari",
  GHS = "Ghanaian Cedi",
  GIP = "Gibraltar Pound",
  GMD = "Gambian Dalasi",
  GNF = "Guinean Franc",
  GTQ = "Guatemalan Quetzal",
  GYD = "Guyanese Dollar",
  HKD = "Hong Kong Dollar",
  HNL = "Honduran Lempira",
  HRK = "Croatian Kuna",
  HTG = "Haitian Gourde",
  HUF = "Hungarian Forint",
  IDR = "Indonesian Rupiah",
  ILS = "Israeli Shekel",
  INR = "Indian Rupee",
  IQD = "Iraqi Dinar",
  IRR = "Iranian Rial",
  ISK = "Icelandic Króna",
  JMD = "Jamaican Dollar",
  JOD = "Jordanian Dinar",
  JPY = "Japanese Yen",
  KES = "Kenyan Shilling",
  KGS = "Kyrgyzstani Som",
  KHR = "Cambodian Riel",
  KMF = "Comorian Franc",
  KRW = "South Korean Won",
  KWD = "Kuwaiti Dinar",
  KYD = "Cayman Islands Dollar",
  KZT = "Kazakhstani Tenge",
  LAK = "Lao Kip",
  LBP = "Lebanese Pound",
  LKR = "Sri Lankan Rupee",
  LRD = "Liberian Dollar",
  LSL = "Lesotho Loti",
  LYD = "Libyan Dinar",
  MAD = "Moroccan Dirham",
  MDL = "Moldovan Leu",
  MGA = "Malagasy Ariary",
  MKD = "Macedonian Denar",
  MMK = "Myanmar Kyat",
  MNT = "Mongolian Tögrög",
  MOP = "Macanese Pataca",
  MRU = "Mauritanian Ouguiya",
  MUR = "Mauritian Rupee",
  MVR = "Maldivian Rufiyaa",
  MWK = "Malawian Kwacha",
  MXN = "Mexican Peso",
  MYR = "Malaysian Ringgit",
  MZN = "Mozambican Metical",
  NAD = "Namibian Dollar",
  NGN = "Nigerian Naira",
  NIO = "Nicaraguan Córdoba",
  NOK = "Norwegian Krone",
  NPR = "Nepalese Rupee",
  NZD = "New Zealand Dollar",
  OMR = "Omani Rial",
  PAB = "Panamanian Balboa",
  PEN = "Peruvian Sol",
  PGK = "Papua New Guinean Kina",
  PHP = "Philippine Peso",
  PKR = "Pakistani Rupee",
  PLN = "Polish Złoty",
  PYG = "Paraguayan Guaraní",
  QAR = "Qatari Riyal",
  RON = "Romanian Leu",
  RSD = "Serbian Dinar",
  RUB = "Russian Ruble",
  RWF = "Rwandan Franc",
  SAR = "Saudi Riyal",
  SBD = "Solomon Islands Dollar",
  SCR = "Seychellois Rupee",
  SDG = "Sudanese Pound",
  SEK = "Swedish Krona",
  SGD = "Singapore Dollar",
  SHP = "Saint Helena Pound",
  SLE = "Sierra Leonean Leone",
  SLL = "Sierra Leonean Leone (Old)",
  SOS = "Somali Shilling",
  SRD = "Surinamese Dollar",
  SSP = "South Sudanese Pound",
  STN = "São Tomé and Príncipe Dobra",
  SYP = "Syrian Pound",
  SZL = "Swazi Lilangeni",
  THB = "Thai Baht",
  TJS = "Tajikistani Somoni",
  TMT = "Turkmenistani Manat",
  TND = "Tunisian Dinar",
  TOP = "Tongan Paanga",
  TRY = "Turkish Lira",
  TTD = "Trinidad and Tobago Dollar",
  TZS = "Tanzanian Shilling",
  UAH = "Ukrainian Hryvnia",
  UGX = "Ugandan Shilling",
  USD = "US Dollar",
  UYU = "Uruguayan Peso",
  UZS = "Uzbekistani So'm",
  VES = "Venezuelan Bolívar",
  VND = "Vietnamese Đồng",
  XAF = "Central African CFA Franc",
  XCD = "East Caribbean Dollar",
  XOF = "West African CFA Franc",
  YER = "Yemeni Rial",
  ZAR = "South African Rand",
  ZMW = "Zambian Kwacha",
}

export enum CurrencySymbolEnum {
  USD = "$", // US Dollar
  EUR = "€", // Euro
  GBP = "£", // British Pound Sterling
  JPY = "¥", // Japanese Yen
  INR = "₹", // Indian Rupee
  AUD = "A$", // Australian Dollar
  CAD = "C$", // Canadian Dollar
  CHF = "CHF", // Swiss Franc
  HKD = "HK$", // Hong Kong Dollar
  SGD = "S$", // Singapore Dollar
  KRW = "₩", // South Korean Won
  BRL = "R$", // Brazilian Real
  ZAR = "R", // South African Rand
  RUB = "₽", // Russian Ruble
  AED = "د.إ", // UAE Dirham
  SAR = "﷼", // Saudi Riyal
  TRY = "₺", // Turkish Lira
  THB = "฿", // Thai Baht
  IDR = "Rp", // Indonesian Rupiah
  MYR = "RM", // Malaysian Ringgit
  PHP = "₱", // Philippine Peso
  PKR = "Rs.", // Pakistani Rupee
}
